create extension if not exists vector with schema public;

create table
  public.articles (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    title text not null,
    embedding vector(1536),
    content text null,
    constraint articles_pkey primary key (id)
  ) tablespace pg_default;